import type { Exporter, Consignee } from './types';

export const mockExporters: Exporter[] = [
  {
    id: 'EXP001',
    nickName: 'TechGlobal',
    companyName: 'TechGlobal Exports Pvt Ltd',
    contactName: 'Rajesh Kumar',
    address: '42, Electronic City Phase-1, Bangalore, Karnataka - 560100',
    country: 'India',
    gstin: '29AABCT1234F1ZH',
    iec: 'AABCT1234F',
    lut: 'LUT/2026/000123',
  },
  {
    id: 'EXP002',
    nickName: 'SilkRoute',
    companyName: 'SilkRoute Trading Corporation',
    contactName: 'Anitha Menon',
    address: '15, Nehru Place, New Delhi - 110019',
    country: 'India',
    gstin: '07BBRPS5678K1Z5',
    iec: 'BBRPS5678K',
    lut: 'LUT/2026/000456',
  },
  {
    id: 'EXP003',
    nickName: 'Spice Valley',
    companyName: 'Spice Valley International',
    contactName: 'Mohammed Ismail',
    address: '78, M.G. Road, Kochi, Kerala - 682016',
    country: 'India',
    gstin: '32AACCS7890L1ZP',
    iec: 'AACCS7890L',
    lut: 'LUT/2026/000789',
  },
  {
    id: 'EXP004',
    nickName: 'OceanCargo',
    companyName: 'Ocean Cargo Logistics Ltd',
    contactName: 'Suresh Reddy',
    address: '23, Jubilee Hills, Hyderabad, Telangana - 500033',
    country: 'India',
    gstin: '36AADCO2345M1ZQ',
    iec: 'AADCO2345M',
    lut: 'LUT/2026/001012',
  },
  {
    id: 'EXP005',
    nickName: 'StarExports',
    companyName: 'Star Exports & Imports',
    contactName: 'Priya Sharma',
    address: '56, Anna Salai, Chennai, Tamil Nadu - 600002',
    country: 'India',
    gstin: '33AAFPS3456N1ZR',
    iec: 'AAFPS3456N',
    lut: 'LUT/2026/001345',
  },
  {
    id: 'EXP006',
    nickName: 'GreenLeaf',
    companyName: 'GreenLeaf Agro Exports',
    contactName: 'Vikram Patel',
    address: '12, CG Road, Ahmedabad, Gujarat - 380009',
    country: 'India',
    gstin: '24AABCG6789P1ZS',
    iec: 'AABCG6789P',
    lut: 'LUT/2026/001678',
  },
  {
    id: 'EXP007',
    nickName: 'RoyalTextile',
    companyName: 'Royal Textile Exports',
    contactName: 'Deepa Nair',
    address: '34, Ring Road, Surat, Gujarat - 395002',
    country: 'India',
    gstin: '24AAECR8901Q1ZT',
    iec: 'AAECR8901Q',
    lut: 'LUT/2026/001901',
  },
  {
    id: 'EXP008',
    nickName: 'Pinnacle',
    companyName: 'Pinnacle Industries International',
    contactName: 'Arun Joshi',
    address: '89, Baner Road, Pune, Maharashtra - 411045',
    country: 'India',
    gstin: '27AAECP1234R1ZU',
    iec: 'AAECP1234R',
    lut: 'LUT/2026/002234',
  },
  {
    id: 'EXP009',
    nickName: 'SunrisePharma',
    companyName: 'Sunrise Pharmaceuticals Export',
    contactName: 'Kavitha Iyer',
    address: '67, MG Road, Indore, Madhya Pradesh - 452001',
    country: 'India',
    gstin: '23AAFCS4567S1ZV',
    iec: 'AAFCS4567S',
    lut: 'LUT/2026/002567',
  },
  {
    id: 'EXP010',
    nickName: 'BlueOcean',
    companyName: 'BlueOcean Marine Exports',
    contactName: 'Ramesh Babu',
    address: '45, Beach Road, Visakhapatnam, AP - 530001',
    country: 'India',
    gstin: '37AABCB7890T1ZW',
    iec: 'AABCB7890T',
    lut: 'LUT/2026/002890',
  },
  {
    id: 'EXP011',
    nickName: 'MetalCraft',
    companyName: 'MetalCraft Exports Corporation',
    contactName: 'Nisha Gupta',
    address: '101, Industrial Area, Ludhiana, Punjab - 141003',
    country: 'India',
    gstin: '03AAGCM9012U1ZX',
    iec: 'AAGCM9012U',
    lut: 'LUT/2026/003123',
  },
  {
    id: 'EXP012',
    nickName: 'GoldenHarvest',
    companyName: 'Golden Harvest Foods Ltd',
    contactName: 'Sanjay Verma',
    address: '22, Civil Lines, Jaipur, Rajasthan - 302006',
    country: 'India',
    gstin: '08AABCG1234V1ZY',
    iec: 'AABCG1234V',
    lut: 'LUT/2026/003456',
  },
];

export const mockConsignees: Consignee[] = [
  {
    id: 'CON001',
    nickName: 'TradeWell',
    companyName: 'TradeWell LLC',
    contactName: 'Michael Johnson',
    address: '1200 Commerce Blvd, Suite 450, Houston, TX 77002',
    country: 'United States',
    contactNo: '+1-713-555-0142',
  },
  {
    id: 'CON002',
    nickName: 'EuroPartners',
    companyName: 'Euro Trading Partners GmbH',
    contactName: 'Hans Mueller',
    address: 'Friedrichstraße 45, 10117 Berlin, Germany',
    country: 'Germany',
    contactNo: '+49-30-555-0198',
  },
  {
    id: 'CON003',
    nickName: 'AsiaLink',
    companyName: 'AsiaLink Import Co Ltd',
    contactName: 'Wei Chen',
    address: '88 Century Avenue, Pudong, Shanghai 200120',
    country: 'China',
    contactNo: '+86-21-5555-0267',
  },
  {
    id: 'CON004',
    nickName: 'CanadaTrade',
    companyName: 'Canada Trade Solutions Inc',
    contactName: 'Sarah Thompson',
    address: '500 Bay Street, Toronto, ON M5G 1L2',
    country: 'Canada',
    contactNo: '+1-416-555-0334',
  },
  {
    id: 'CON005',
    nickName: 'GulfLogistics',
    companyName: 'Gulf Logistics & Trading FZE',
    contactName: 'Ahmed Al Maktoum',
    address: 'Jebel Ali Free Zone, P.O. Box 17000, Dubai',
    country: 'UAE',
    contactNo: '+971-4-555-0421',
  },
  {
    id: 'CON006',
    nickName: 'NipponImport',
    companyName: 'Nippon Import Corporation',
    contactName: 'Takeshi Yamamoto',
    address: '2-3-1 Nihonbashi, Chuo-ku, Tokyo 103-0027',
    country: 'Japan',
    contactNo: '+81-3-5555-0589',
  },
  {
    id: 'CON007',
    nickName: 'AussieTrade',
    companyName: 'Aussie Trade Connect Pty Ltd',
    contactName: 'James Wilson',
    address: '200 George Street, Sydney, NSW 2000',
    country: 'Australia',
    contactNo: '+61-2-5555-0634',
  },
  {
    id: 'CON008',
    nickName: 'BritishImport',
    companyName: 'British Import Holdings PLC',
    contactName: 'David Brown',
    address: '50 Canary Wharf, London E14 5AB',
    country: 'United Kingdom',
    contactNo: '+44-20-5555-0712',
  },
  {
    id: 'CON009',
    nickName: 'SingaporeHub',
    companyName: 'Singapore Trade Hub Pte Ltd',
    contactName: 'Lim Wei Ming',
    address: '1 Raffles Place, #20-01, Singapore 048616',
    country: 'Singapore',
    contactNo: '+65-5555-0890',
  },
  {
    id: 'CON010',
    nickName: 'BrazilConnect',
    companyName: 'Brazil Connect Importação LTDA',
    contactName: 'Carlos Silva',
    address: 'Av. Paulista 1578, São Paulo, SP 01310-200',
    country: 'Brazil',
    contactNo: '+55-11-5555-0945',
  },
  {
    id: 'CON011',
    nickName: 'KoreaImport',
    companyName: 'Korea Import Solutions Co Ltd',
    contactName: 'Park Ji-hoon',
    address: '123 Gangnam-daero, Gangnam-gu, Seoul 06164',
    country: 'South Korea',
    contactNo: '+82-2-5555-1023',
  },
];
